namespace Ged.Core.Model;

/// <summary>
/// A geometry face (RFL <c>face</c>). All fields, including the two reserved
/// slots and the always-zero padding, are preserved for lossless round-trips.
/// </summary>
public sealed class Face
{
    public RfPlane Plane { get; set; }

    /// <summary>Index into the geometry texture table, or -1 for a portal.</summary>
    public int Texture { get; set; }

    /// <summary>Index into the geometry surface table, or -1 if the face has no lightmap.</summary>
    public int SurfaceIndex { get; set; }

    public int FaceId { get; set; }

    /// <summary>Two reserved ints (rfl.ksy <c>reserved1</c>, always -1). Preserved exactly.</summary>
    public int Reserved1A { get; set; } = -1;

    public int Reserved1B { get; set; } = -1;

    /// <summary>portals index + 2 if the face was generated by a portal, else 0.</summary>
    public int PortalIndexPlus2 { get; set; }

    public ushort Flags { get; set; }

    /// <summary>rfl.ksy <c>reserved2</c> (always 0). Preserved exactly.</summary>
    public ushort Reserved2 { get; set; }

    public uint SmoothingGroups { get; set; }

    /// <summary>Index into the geometry room table, or -1 in movers.</summary>
    public int RoomIndex { get; set; }

    public List<FaceVertex> Vertices { get; set; } = new();

    /// <summary>2-bit lightmap resolution (0 lowest .. 3 highest).</summary>
    public int LightmapResolution => (Flags & (ushort)FaceFlags.LightmapResolutionMask) >> 8;

    /// <summary>
    /// True when the face is a portal face for render-side classification (View ▸
    /// Portal Faces). The RFL format carries two independent portal markers and a
    /// face is a portal face if EITHER holds: the portal-texture sentinel
    /// (<see cref="Texture"/> &lt; 0), or membership in a portal via
    /// <see cref="PortalIndexPlus2"/> (&gt;= 2 ⇒ portal k = value − 2; 0/1 ⇒ not a
    /// portal). Community maps (e.g. ctfstockintradeb1.rfl) carry portal faces with a
    /// REAL texture index but a nonzero <c>portal_index_plus_2</c>, so testing the
    /// texture sentinel alone misses them.
    /// </summary>
    public bool IsPortalFace => Texture < 0 || PortalIndexPlus2 >= 2;
}
