<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Ged.Rendering</RootNamespace>
    <AssemblyName>Ged.Rendering</AssemblyName>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ged.Core\Ged.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Ged.Rendering.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Silk.NET.Direct3D.Compilers" Version="2.22.0" />
    <PackageReference Include="Silk.NET.Direct3D11" Version="2.22.0" />
    <PackageReference Include="Silk.NET.DXGI" Version="2.22.0" />
    <PackageReference Include="Silk.NET.Maths" Version="2.22.0" />
    <PackageReference Include="Silk.NET.OpenGL" Version="2.22.0" />
  </ItemGroup>

</Project>
