using System;
using System.Collections.Generic;
using System.Linq;
using Ged.Core.Compiler;
using Ged.Core.Model;
using Xunit;

namespace Ged.Core.Tests.Compiler;

/// <summary>
/// Per-flag derivation gate for the five BUILD-GENERATED face flags. RED does NOT let the
/// author set these as face attributes — it regenerates them at build time from the texture,
/// the brush, and the liquid room:
/// <list type="bullet">
/// <item>has_alpha (0x40) / has_holes (0x80): RED.exe FlagFaceTextureTraits (FUN_0041d3c0)
///   CLEARS both, then re-sets them only on DETAIL faces whose texture has an alpha channel
///   (holes unless the name is a "gls_" glass prefix). Structural faces are always opaque.</item>
/// <item>is_invisible (0x2000): FlagFaceTextureTraits clears it, then sets it when the texture
///   name contains "invisible" (rfl.ksy face flags doc; RF invisible walls are opaque TGAs).</item>
/// <item>is_detail (0x08): a BRUSH property — set on a face iff its source brush is a detail
///   brush (rfl.ksy: "used in static_geometry but not in brushes").</item>
/// <item>liquid_surface (0x04): "face generated by liquid room effect" — emitted by the liquid
///   surface builder from the liquid room, never authored on a brush face.</item>
/// </list>
/// These tests pin GED's compiler to that behaviour on synthetic brushes (no corpus / VFS).
/// </summary>
public sealed class FaceFlagDerivationTests
{
    private const ushort Detail = (ushort)FaceFlags.IsDetail;
    private const ushort HasAlpha = (ushort)FaceFlags.HasAlpha;
    private const ushort HasHoles = (ushort)FaceFlags.HasHoles;
    private const ushort Invisible = (ushort)FaceFlags.IsInvisible;
    private const ushort Liquid = (ushort)FaceFlags.LiquidSurface;

    private static Vec3 V(float x, float y, float z) => new(x, y, z);

    private static Geometry Compile(
        List<Brush> brushes,
        Func<string, TextureTraits?>? traits = null,
        IReadOnlyList<RoomEffect>? effects = null) =>
        GeometryCompiler.Compile(
            brushes,
            effects,
            new CompileOptions { BuildSurfaces = false, TextureTraits = traits }).Geometry;

    private static List<Face> FacesWith(Geometry g, string texture)
    {
        int idx = g.Textures.FindIndex(t => string.Equals(t, texture, StringComparison.OrdinalIgnoreCase));
        return idx < 0 ? new List<Face>() : g.Faces.Where(f => f.Texture == idx).ToList();
    }

    /// <summary>An alpha texture on a DETAIL brush earns has_alpha + has_holes + is_detail.</summary>
    [Fact]
    public void Alpha_Texture_On_Detail_Brush_Sets_Alpha_Holes_And_Detail()
    {
        var brushes = new List<Brush>
        {
            CompilerTestBrushes.AirBox(1, V(0, 0, 0), 20, 20, 20, "wall"),
            CompilerTestBrushes.DetailBox(2, V(0, 0, 0), 4, 4, 4, texture: "grate.tga"),
        };

        Geometry g = Compile(brushes, n => n == "grate.tga" ? new TextureTraits(false, true, true) : TextureTraits.None);
        List<Face> grate = FacesWith(g, "grate.tga");

        Assert.NotEmpty(grate);
        Assert.All(grate, f =>
        {
            Assert.True((f.Flags & Detail) != 0, "detail brush face lost its is_detail bit");
            Assert.True((f.Flags & HasAlpha) != 0, "detail alpha texture did not set has_alpha");
            Assert.True((f.Flags & HasHoles) != 0, "detail alpha texture did not set has_holes");
        });
    }

    /// <summary>The SAME alpha texture on a STRUCTURAL brush stays opaque (RED's detail-bit gate).</summary>
    [Fact]
    public void Alpha_Texture_On_Structural_Brush_Stays_Opaque()
    {
        var brushes = new List<Brush>
        {
            CompilerTestBrushes.AirBox(1, V(0, 0, 0), 20, 20, 20, "wall"),
            CompilerTestBrushes.SolidBox(2, V(0, -8, 0), 6, 4, 6, "sign.tga"), // sits on the floor
        };

        Geometry g = Compile(brushes, n => n == "sign.tga" ? new TextureTraits(false, true, true) : TextureTraits.None);
        List<Face> sign = FacesWith(g, "sign.tga");

        Assert.NotEmpty(sign);
        Assert.All(sign, f =>
        {
            Assert.True((f.Flags & Detail) == 0, "a structural brush face must not be detail");
            Assert.True((f.Flags & HasAlpha) == 0, "structural face wrongly alpha-blended (defect 1)");
            Assert.True((f.Flags & HasHoles) == 0, "structural face wrongly has_holes");
        });
    }

    /// <summary>
    /// The gap fix: an authored 0x40/0x80 on a structural face is DISCARDED at build. RED clears
    /// the bits up front and never re-sets them on a non-detail face, so a legacy/imported brush
    /// that carries them must still compile opaque.
    /// </summary>
    [Fact]
    public void Authored_Alpha_On_Structural_Face_Is_Cleared_By_Build()
    {
        Brush solid = CompilerTestBrushes.SolidBox(2, V(0, -8, 0), 6, 4, 6, "authored.tga");
        foreach (Face f in solid.Geometry.Faces)
        {
            f.Flags |= (ushort)(HasAlpha | HasHoles); // author the bits RED derives
        }

        var brushes = new List<Brush> { CompilerTestBrushes.AirBox(1, V(0, 0, 0), 20, 20, 20, "wall"), solid };

        // No trait provider at all: nothing tells the compiler this texture has alpha.
        Geometry g = Compile(brushes, traits: null);
        List<Face> authored = FacesWith(g, "authored.tga");

        Assert.NotEmpty(authored);
        Assert.All(authored, f =>
        {
            Assert.True((f.Flags & HasAlpha) == 0, "authored has_alpha survived onto a structural wall");
            Assert.True((f.Flags & HasHoles) == 0, "authored has_holes survived onto a structural wall");
        });
    }

    /// <summary>An *invisible* texture name marks the face invisible (name rule, no VFS needed).</summary>
    [Fact]
    public void Invisible_Texture_Name_Sets_Invisible()
    {
        var brushes = new List<Brush>
        {
            CompilerTestBrushes.AirBox(1, V(0, 0, 0), 20, 20, 20, "wall"),
            CompilerTestBrushes.SolidBox(2, V(0, -8, 0), 6, 4, 6, "mtl_invisible02.tga"),
        };

        Geometry g = Compile(brushes, traits: null); // name-only rule
        List<Face> inv = FacesWith(g, "mtl_invisible02.tga");

        Assert.NotEmpty(inv);
        Assert.All(inv, f => Assert.True((f.Flags & Invisible) != 0, "invisible-named texture did not set is_invisible"));
    }

    /// <summary>is_detail is a brush property: detail-brush faces carry it, structural faces never do.</summary>
    [Fact]
    public void Detail_Bit_Is_Derived_From_The_Brush()
    {
        var brushes = new List<Brush>
        {
            CompilerTestBrushes.AirBox(1, V(0, 0, 0), 20, 20, 20, "wall"),
            CompilerTestBrushes.DetailBox(2, V(5, 0, 0), 3, 3, 3, texture: "detail.tga"),
            CompilerTestBrushes.SolidBox(3, V(0, -8, 0), 4, 3, 4, "struct.tga"),
        };

        Geometry g = Compile(brushes, traits: null);
        List<Face> detail = FacesWith(g, "detail.tga");
        List<Face> structural = FacesWith(g, "struct.tga");

        Assert.NotEmpty(detail);
        Assert.All(detail, f => Assert.True((f.Flags & Detail) != 0, "detail brush face missing is_detail"));

        Assert.NotEmpty(structural);
        Assert.All(structural, f => Assert.True((f.Flags & Detail) == 0, "structural brush face wrongly is_detail"));
    }

    /// <summary>The liquid surface is generated from the liquid room and carries liquid_surface (0x04).</summary>
    [Fact]
    public void Liquid_Room_Generates_Liquid_Surface_Faces()
    {
        var brushes = new List<Brush> { CompilerTestBrushes.AirBox(1, V(0, 0, 0), 10, 10, 10, "wall") };
        var effect = new RoomEffect
        {
            EffectType = Ged.Core.IO.Rfl.Sections.RoomEffectsSection.EffectLiquidRoom,
            LiquidProperties = new RoomEffectLiquidProperties
            {
                Depth = 4f,
                LiquidType = 1,
                SurfaceTexture = "wtr_pool01.tga",
                Waveform = 2,
            },
            Header = new ObjectHeader { Uid = 5000, Position = V(0, 0, 0) },
        };

        Geometry g = Compile(brushes, traits: null, effects: new[] { effect });
        List<Face> liquid = g.Faces.Where(f => (f.Flags & Liquid) != 0).ToList();

        Assert.NotEmpty(liquid);
        Assert.All(liquid, f =>
        {
            Assert.True(f.Texture >= 0 && f.Texture < g.Textures.Count);
            Assert.Equal("wtr_pool01.tga", g.Textures[f.Texture]);
        });

        // No brush authored the flag — it is purely generated.
        Assert.DoesNotContain(brushes[0].Geometry.Faces, f => (f.Flags & Liquid) != 0);
    }
}
